<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1735568717092' stop='1735568717667'>
    <name>API Testing for Login</name>
    <title>API Testing for Login</title>
    <test-cases>
        <test-case start='1735568717112' status='broken' stop='1735568717312'>
            <name>Login with user credentials</name>
            <title>Login with user credentials</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>_login.default.loginUser is not a function</message>
                <stack-trace>TypeError: _login.default.loginUser is not a function
                    at Context.eval (cypress/e2e/TestCases/APIGetTest/LoginTest.cy.js:7:8)
                    at Context.resolveAndRunStepDefinition (node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:193:0)
                    at Context.eval (node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js:27:0)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735568717356' status='broken' stop='1735568717515'>
            <name>Login with admin credentials</name>
            <title>Login with admin credentials</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>_login.default.loginUser is not a function</message>
                <stack-trace>TypeError: _login.default.loginUser is not a function
                    at Context.eval (cypress/e2e/TestCases/APIGetTest/LoginTest.cy.js:7:8)
                    at Context.resolveAndRunStepDefinition (node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:193:0)
                    at Context.eval (node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js:27:0)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735568717534' status='broken' stop='1735568717664'>
            <name>Login with invalid credentials</name>
            <title>Login with invalid credentials</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>_login.default.loginUser is not a function</message>
                <stack-trace>TypeError: _login.default.loginUser is not a function
                    at Context.eval (cypress/e2e/TestCases/APIGetTest/LoginTest.cy.js:7:8)
                    at Context.resolveAndRunStepDefinition (node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:193:0)
                    at Context.eval (node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js:27:0)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>